model_paramerters:
  class_names: ["Human","AI"]
  num_classes: 2
  num_folds: 5
  seed: 42
  max_sequence: 250    
  max_tokens: 35000
  batch_size: 32
  selected_folds: [0,1,3]
  ml_lr: 0.00001
  embd_dim: 150
  epochs: 1