artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train_data
  test_data_path: artifacts/data_ingestion/test_data
  raw_train_data_path: src/llmTextDetection/data/train
  raw_test_data_path: src/llmTextDetection/data/test
  pre_processing_path: artifacts/data_ingestion/pre_processing

model_trainer:
    root_dir: artifacts/model_trainer
    vectorizer_path: artifacts/model_trainer/vectorizers
    model_path: artifacts/model_trainer/models
    
predictor:
    models_root: artifacts/model_trainer/models
    vectorizers_root: artifacts/model_trainer/vectorizers

evaluator:
    root: artifacts/evaluator/scores
    ml_flow_uri: https://dagshub.com/anoopgeorg/llm-text-detection.mlflow
    ml_flow_uname: anoopgeorg
    ml_flow_pass: 
    eval_model_path: artifacts/evaluator/models