artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train_data
  test_data_path: artifacts/data_ingestion/test_data
  raw_train_data_path: src/llmTextDetection/data/train
  raw_test_data_path: src/llmTextDetection/data/test
  