artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train_data
  test_data_path: artifacts/data_ingestion/test_data
  raw_train_data_path: src/llmTextDetection/data/train
  raw_test_data_path: src/llmTextDetection/data/test

model_trainer:
    root_dir: artifacts/model_trainer
    vectorizer_path: artifacts/model_trainer/vectorizers
    model_path: artifacts/model_trainer/models
    
predictor:
    models_root: artifacts/model_trainer/models
    vectorizers_root: artifacts/model_trainer/vectorizers